Resources:
  TelegramIngressRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: &lambdaAssumeRole
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns: &lambdaBasicExecution
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: enqueue-ingress-workers
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource:
                  - Fn::GetAtt:
                      - TelegramReplyWorkerQueue
                      - Arn
                  - Fn::GetAtt:
                      - TelegramAgentWorkerQueue
                      - Arn
                  - Fn::GetAtt:
                      - TelegramActivityWorkerQueue
                      - Arn
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                Resource:
                  - arn:aws:dynamodb:*:*:table/${self:custom.chatConfigurationTableName}

  TelegramAdminApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: *lambdaAssumeRole
      ManagedPolicyArns: *lambdaBasicExecution
      Policies:
        - PolicyName: administer-chat-configuration
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Resource:
                  - arn:aws:dynamodb:*:*:table/${self:custom.chatConfigurationTableName}
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource:
                  - arn:aws:dynamodb:*:*:table/${self:custom.chatUserStatisticsTableName}
                  - arn:aws:dynamodb:*:*:table/${self:custom.chatUserStatisticsTableName}/index/${self:custom.chatUserStatisticsUserIdIndexName}

  TelegramReplyWorkerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: *lambdaAssumeRole
      ManagedPolicyArns: *lambdaBasicExecution
      Policies:
        - PolicyName: reply-worker-aws-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - arn:aws:lambda:*:*:${self:service}-${sls:stage}-sharp-renderer
              - Effect: Allow
                Action:
                  - dynamodb:Query
                Resource:
                  - arn:aws:dynamodb:*:*:table/${self:custom.chatUserStatisticsTableName}
                  - arn:aws:dynamodb:*:*:table/${self:custom.chatEventsTableName}
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource:
                  - arn:aws:dynamodb:*:*:table/${self:custom.chatUserStatisticsTableName}
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                Resource:
                  - arn:aws:dynamodb:*:*:table/${self:custom.chatConfigurationTableName}
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource:
                  - Fn::GetAtt:
                      - TelegramReplyWorkerQueue
                      - Arn

  TelegramAgentWorkerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: *lambdaAssumeRole
      ManagedPolicyArns: *lambdaBasicExecution
      Policies:
        - PolicyName: invoke-sharp-renderer
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - arn:aws:lambda:*:*:${self:service}-${sls:stage}-sharp-renderer
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource:
                  - Fn::GetAtt:
                      - TelegramAgentWorkerQueue
                      - Arn
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                Resource:
                  - arn:aws:dynamodb:*:*:table/${self:custom.chatConfigurationTableName}

  TelegramActivityWorkerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: *lambdaAssumeRole
      ManagedPolicyArns: *lambdaBasicExecution
      Policies:
        - PolicyName: track-chat-activity
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource:
                  - arn:aws:dynamodb:*:*:table/${self:custom.chatUserStatisticsTableName}
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource:
                  - arn:aws:dynamodb:*:*:table/${self:custom.chatEventsTableName}
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                Resource:
                  - arn:aws:dynamodb:*:*:table/${self:custom.chatConfigurationTableName}
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - arn:aws:lambda:*:*:${self:service}-${sls:stage}-websocket-broadcast-stats
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource:
                  - Fn::GetAtt:
                      - TelegramActivityWorkerQueue
                      - Arn

  CurrencySchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: *lambdaAssumeRole
      ManagedPolicyArns: *lambdaBasicExecution
      Policies:
        - PolicyName: invoke-sharp-renderer
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - arn:aws:lambda:*:*:${self:service}-${sls:stage}-sharp-renderer

  SharpRendererRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: *lambdaAssumeRole
      ManagedPolicyArns: *lambdaBasicExecution
      Policies:
        - PolicyName: read-chat-events
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                Resource:
                  - arn:aws:dynamodb:*:*:table/${self:custom.chatEventsTableName}

  WebsocketConnectRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: *lambdaAssumeRole
      ManagedPolicyArns: *lambdaBasicExecution
      Policies:
        - PolicyName: create-websocket-connection
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                Resource:
                  - arn:aws:dynamodb:*:*:table/${self:custom.websocketConnectionsTableName}

  WebsocketDisconnectRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: *lambdaAssumeRole
      ManagedPolicyArns: *lambdaBasicExecution
      Policies:
        - PolicyName: delete-websocket-connection
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DeleteItem
                Resource:
                  - arn:aws:dynamodb:*:*:table/${self:custom.websocketConnectionsTableName}

  WebsocketStatsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: *lambdaAssumeRole
      ManagedPolicyArns: *lambdaBasicExecution
      Policies:
        - PolicyName: websocket-stats-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource:
                  - arn:aws:dynamodb:*:*:table/${self:custom.websocketConnectionsTableName}
              - Effect: Allow
                Action:
                  - dynamodb:Query
                Resource:
                  - arn:aws:dynamodb:*:*:table/${self:custom.chatUserStatisticsTableName}
                  - arn:aws:dynamodb:*:*:table/${self:custom.chatEventsTableName}
              - Effect: Allow
                Action:
                  - execute-api:ManageConnections
                Resource:
                  - Fn::Join:
                      - ''
                      - - 'arn:aws:execute-api:'
                        - Ref: AWS::Region
                        - ':'
                        - Ref: AWS::AccountId
                        - ':'
                        - Ref: WebsocketsApi
                        - /${sls:stage}/POST/@connections/*
