Resources:
  ChatWebsocketConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.websocketConnectionsTableName}
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
        - AttributeName: chatId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ${self:custom.websocketConnectionsChatIdIndexName}
          KeySchema:
            - AttributeName: chatId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  ChatStatisticsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: chat-statistics
      AttributeDefinitions:
        - AttributeName: chatId
          AttributeType: S
      KeySchema:
        - AttributeName: chatId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ChatEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: chat-events
      AttributeDefinitions:
        - AttributeName: chatId
          AttributeType: S
        - AttributeName: date
          AttributeType: N
      KeySchema:
        - AttributeName: chatId
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  WebSocketUrl:
    Description: WebSocket API URL for telegram-bot-ui CONFIG.wss
    Value:
      Fn::Join:
        - ''
        - - wss://
          - Ref: WebsocketsApi
          - .execute-api.
          - Ref: AWS::Region
          - .
          - Ref: AWS::URLSuffix
          - /${sls:stage}

  SearchApiUrl:
    Description: REST API base URL for telegram-bot-ui CONFIG.rest
    Value:
      Fn::Join:
        - ''
        - - https://
          - Ref: ApiGatewayRestApi
          - .execute-api.
          - Ref: AWS::Region
          - .
          - Ref: AWS::URLSuffix
          - /${sls:stage}
