name: Deploy Latest Master

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun lint
      - run: bun tsc
      - run: bun run test
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
      - run: bun run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          GOOGLE_CX_TOKEN: ${{secrets.GOOGLE_CX_TOKEN}}
          GOOGLE_API_KEY: ${{secrets.GOOGLE_API_KEY}}
          OPEN_WEATHER_MAP_TOKEN: ${{secrets.OPEN_WEATHER_MAP_TOKEN}}
          TOKEN: ${{secrets.TOKEN}}
          YOUTUBE_TOKEN: ${{secrets.YOUTUBE_TOKEN}}
          FIXER_API_KEY: ${{secrets.FIXER_API_KEY}}
          EXCHANGE_RATE_API_KEY: ${{secrets.EXCHANGE_RATE_API_KEY}}
          COIN_MARKET_CAP_API_KEY: ${{secrets.COIN_MARKET_CAP_API_KEY}}
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          OPENAI_CHAT_IDS: ${{secrets.OPENAI_CHAT_IDS}}